### ISSUE TITLE
Does this still work for installing global.json dotnet version?

### ISSUE THREAD

**Issue by davidje13** [JosephWoodward/DotNetInstallSdkGlobalTool#14] opened 2019-10-09 11:14 UTC
I am trying to automatically install the correct dotnet SDK version in my project.

The recommended setup appears to be:

```bash
# (from the directory which contains global.json)
dotnet tool install -g installsdkglobaltool
dotnet install-sdk
dotnet restore # (or whatever)
```

But even the first command fails with:

> A compatible SDK version for global.json version: [2.2.105] from [(path)\global.json] was not found

So I tried an alternative:

```bash
cd ..
dotnet tool install -g installsdkglobaltool

cd myProject
dotnet install-sdk
dotnet restore # (or whatever)
```

now `dotnet install-sdk` fails in the same way.

This seems unsolvable, since I can't run `dotnet install-sdk` in the directory with global.json, and I can't run it outside the directory since it won't find the file.

Am I using this correctly? Is this a regression? I found https://github.com/dotnet/sdk/issues/2334 which looks related, and added a comment there too.

Version details:

```
dotnet --version
> 2.2.401

dotnet --list-sdks
> 2.2.401 [C:\Program Files\dotnet\sdk]

dotnet --list-runtimes
> Microsoft.AspNetCore.All 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
> Microsoft.AspNetCore.App 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
> Microsoft.NETCore.App 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

cat myProject/global.json
> {
>   "sdk": {
>     "version": "2.2.105"
>   }
> }
```

**Comment by josephwoodward** [comment] 2019-10-09 11:54
Thanks for raising this @davidje13, I'll take a look as it should work.

**Comment by slang25** [comment] 2019-10-09 13:02
Confirmed here

**Comment by josephwoodward** [comment] 2019-10-09 14:08
> Confirmed here

Confirmed that it's working, or that it's not working?

**Comment by slang25** [comment] 2019-10-09 14:11
😄 good point, confirmed it's an issue. My guess is v3 of the dotnet cli has changed the behaviour and now tools require runtime specified in the global.json, in which case this tool would have to run outside of the global JSON it wants to download the SDK for.

**Comment by davidje13** [comment] 2019-10-09 14:13
Easiest fix is presumably to allow specifying a path to the desired global.json when running the command? (rather than auto-discovering)

Although it would be nice if this could be fixed upstream.

**Comment by davidje13** [comment] 2019-10-09 14:44
Following a suggestion on the other thread, invoking as `dotnet-install-sdk` (rather than `dotnet install-sdk`) gets further, but then errors with:

```
Running in headless mode
A compatible SDK version for global.json version: [2.2.105] from [(path)\global.json] was not found
Starting download of .NET Core SDK Version 2.2.105

Unhandled Exception:
Unhandled Exception:
Unhandled Exception:
Unhandled Exception:
Unhandled Exception:
Unhandled Exception: System.IO.IOException: The handle is invalid
   at System.ConsolePal.GetBufferInfo(Boolean throwOnNoConsole, Boolean& succeeded)
   at DotNet.InstallSdk.SdkAcquirer.<>c__DisplayClass6_2.<Acquire>b__3(Object sender, Int64 totalBytes) in /Users/joseph.woodward/Documents/git/Personal/DotNetInstallSdkGlobalTool/src/DotNetInstallSdk/SdkAcquirer.cs:line 84
   at System.Threading.QueueUserWorkItemCallbackDefaultContext`1.<>c.<.cctor>b__5_0(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
System.IO.IOException: The handle is invalid
   at System.ConsolePal.GetBufferInfo(Boolean throwOnNoConsole, Boolean& succeeded)
   at DotNet.InstallSdk.SdkAcquirer.<>c__DisplayClass6_2.<Acquire>b__3(Object sender, Int64 totalBytes) in /Users/joseph.woodward/Documents/git/Personal/DotNetInstallSdkGlobalTool/src/DotNetInstallSdk/SdkAcquirer.cs:line 84
   at System.Threading.QueueUserWorkItemCallbackDefaultContext`1.<>c.<.cctor>b__5_0(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
System.IO.IOException: The handle is invalid
   at System.ConsolePal.GetBufferInfo(Boolean throwOnNoConsole, Boolean& succeeded)
   at DotNet.InstallSdk.SdkAcquirer.<>c__DisplayClass6_2.<Acquire>b__3(Object sender, Int64 totalBytes) in /Users/joseph.woodward/Documents/git/Personal/DotNetInstallSdkGlobalTool/src/DotNetInstallSdk/SdkAcquirer.cs:line 84
   at System.Threading.QueueUserWorkItemCallbackDefaultContext`1.<>c.<.cctor>b__5_0(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
System.IO.IOException: The handle is invalid
   at System.ConsolePal.GetBufferInfo(Boolean throwOnNoConsole, Boolean& succeeded)
   at DotNet.InstallSdk.SdkAcquirer.<>c__DisplayClass6_2.<Acquire>b__3(Object sender, Int64 totalBytes) in /Users/joseph.woodward/Documents/git/Personal/DotNetInstallSdkGlobalTool/src/DotNetInstallSdk/SdkAcquirer.cs:line 84
   at System.Threading.QueueUserWorkItemCallbackDefaultContext`1.<>c.<.cctor>b__5_0(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
System.IO.IOException: The handle is invalid
   at System.ConsolePal.GetBufferInfo(Boolean throwOnNoConsole, Boolean& succeeded)
   at DotNet.InstallSdk.SdkAcquirer.<>c__DisplayClass6_2.<Acquire>b__3(Object sender, Int64 totalBytes) in /Users/joseph.woodward/Documents/git/Personal/DotNetInstallSdkGlobalTool/src/DotNetInstallSdk/SdkAcquirer.cs:line 84
   at System.Threading.QueueUserWorkItemCallbackDefaultContext`1.<>c.<.cctor>b__5_0(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
System.IO.IOException: The handle is invalid
   at System.ConsolePal.GetBufferInfo(Boolean throwOnNoConsole, Boolean& succeeded)
   at DotNet.InstallSdk.SdkAcquirer.<>c__DisplayClass6_2.<Acquire>b__3(Object sender, Int64 totalBytes) in /Users/joseph.woodward/Documents/git/Personal/DotNetInstallSdkGlobalTool/src/DotNetInstallSdk/SdkAcquirer.cs:line 84
   at System.Threading.QueueUserWorkItemCallbackDefaultContext`1.<>c.<.cctor>b__5_0(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
```

I'm guessing this is because the tool needs to be invoked through `dotnet`, but posting here in case there's a known fix.

**Comment by nguerrera** [comment] 2019-10-09 15:01
> My guess is v3 of the dotnet cli has changed the behaviour

There were a few bugs that would have allowed a limited set of installing newer sdk in global.json than what you have to accidentally work. And it would have worked to install an older version. But fundamentally, expecting to be a dotnet sub-command and also be able to run when global.json can't be matched never would never have fully worked. The code that reads global.json happens at startup in native code and picks the dotnet.dll that will interpret "dotnet install-sdk". If it can't find a dotnet.dll that matches the global.json, there's no way for the command to continue to be interpreted.

**Comment by slang25** [comment] 2019-10-09 15:06
I've read that native code and can tell you that it did work though. It may not have been by design, and I suspect it's now fixed as we relied on that behaviour.

Update: I've read [your comment here](https://github.com/dotnet/sdk/issues/2334#issuecomment-540028242) and that makes sense, I've always had a least 1 version of 2.1.x and 2.2.x so that would have explained what I was seeing.

**Comment by josephwoodward** [comment] 2020-05-26 23:51
Going to close this as whilst it's recommended not to use the `dotnet` command, the `dotnet-install-sdk` command still works as expected.

**Closed as completed by josephwoodward** 2020-05-26 23:51 UTC
